const dateCelebrations = [
  "Merry Christmas",
  "Happy Friday",
  "Happy Saturday",
  "Happy Christmas Eve",
  "Merry Christmas eve",
  "Happy Solstice",
  "Happy Sunday",
  "It's the weekend",
  ", and a summer of gloriously long evenings full of sunlight awaits you",
  "You made it to another weekend",
  "You made it to the end of the week",
]

const updates = [
  "5 seconds is hardly any time, it's a deep breath",
  "5.30 sunset is just around the corner",
  "5.30pm is an okay time to get dark",
  "5.45pm sunset today, that’s almost like a proper day",
  "As a reward, sunset ticked forward to 4.59pm today and there were a whole 20 seconds of extra daylight -- that's a whole minute since the solstice",
]

const uncategorized = [
  "As icing on the cake it's also a double day: sunrise went back to 7.17am",
  "At 10 hours and 37 minutes, the last time the day was this long was November 1st last year",
  "At 10 hours and 40 minutes long, this is the longest day since October 30th last year, which is more than 100 days ago",
  "At 29 days (it's a leap year",
  "At least 2 full extra minutes of daylight every day from here on out",
  "Before this week is out we’ll be getting 2 minutes extra every day",
  "Beginning to sound okay, right?",
  "But at 10 hours and 45 minutes long, this is the most daylight you’ve had since October 27th",
  "But at least today is a triple day",
  "But every day, a minute better",
  "But it's *more*. And tomorrow will be longer, and the day after that, and each day the number of seconds added will be more than the day before, until we add minutes at a time",
  "But it's really been loaded into the last few days, adding 1 minute and 45 seconds of daylight just today",
  "But it's sunrise/sunset times",
  "But it's twice as much extra as yesterday",
  "But it’s not going to just stop being terrible; it’s going to start being good",
  "But on the other hand, today had 5 whole minutes more daylight than the solstice did",
  "But sunset ticked forward to 4.58pm and there were 16 whole seconds of extra daylight",
  "But tomorrow is a really nice milestone, so hold on",
  "But we’ve got through this before, and we’ll do it again",
  "Celebrate every little milestone",
  "Compared to the rest of it this is gonna be easy",
  "Congratulations",
  "Cool",
  "Courage",
  "Daylight is really beginning to rack up quickly now; you've gained 4 minutes in just a week",
  "Days are already 10 minutes longer than they were on January 1.",
  "Days are already 5 minutes longer than they were on January 1",
  "Days are beginning to feel of okay length again",
  "Double days are getting more and more common",
  "Double days are gonna happen a lot more often",
  "Each day gets longer faster than the one before",
  "Each day will have more extra time than the day before",
  "Enjoy the summer, and I'll be here when you need me again",
  "Enjoy the summer, and the next time you need me, I'll be here",
  "Enjoy your weekend full of daylight",
  "Every day at least a minute more",
  "Every day from now on has at least a minute more daylight than the one before",
  "Every day from now on will be at least a minute longer than the one before, so we'll be moving a lot faster now",
  "Every day until spring, days get longer by larger and larger amounts every day",
  "Every day you'll get more daylight than the day before, *and* the amount more you get will keep getting larger",
  'Every year I google why it\'s called "Boxing day"and the result is always a dissatisfying bunch of semi-apocryphal stories',
  "Everything is great",
  "February has added a whole 46 minutes of daylight so far",
  "February is half over",
  "First, it's the first triple day",
  "From here on out, every day is at least 2 minutes longer",
  "From here on out, every day will be better",
  "From now on every sunrise will be earlier than the day before, and we'll track that as well",
  "From now on we add at least 2 more minutes every day",
  "From now on you'll be getting at least half a minute of extra daylight every single day to carry you through",
  "Fuck it",
  "Fun fact: sunset rolls back faster than sunrise does",
  "Get hype",
  "Getting faster all the time",
  "Getting faster",
  "Give me a follow if you're in the DMV and want a dose of happiness every day as the sun comes out just a bit more each day",
  "Glorious",
  "Go you",
  "Great weather, long days still getting longer",
  "Halfway through February",
  "Hang in there",
  "Hang on tight, we’re nearly there",
  "Happy Friday",
  "Happy max derivative day, everybody",
  "Have 1 minute and 55 seconds extra daylight to celebrate",
  "Have 1 minute and 56 seconds of extra daylight to celebrate",
  "Have 2 minutes and 26 seconds of extra daylight, and tomorrow is the BIG milestone",
  "Have a good weekend",
  "Have a relaxing Sunday",
  "Have another 2 minutes and 23 seconds of daylight to cap off the month",
  "Have courage",
  "Here Comes The Sun is back this year and starts tweeting tomorrow, the solstice",
  "Here we go…",
  "Here, have 1 minute and 55 seconds of extra daylight",
  "Hooray",
  "I am so proud of you for stick with us all so long",
  "I believe in you",
  "I can deal with 5.57pm, but we can do better",
  "I got you 11 precious extra seconds of daylight",
  "I got you 12 extra seconds of daylight, and thanks to a trick of the clock sunset ticked forward by 1 minute to 4.56pm",
  "I got you 12 seconds of extra daylight and a promise of many more",
  "I got you 6 extra seconds of daylight, and a promise of more every day",
  "I know it still sucks",
  "I know it’s not much, but it’s a start, and we’ll get there together",
  "I know it’s still dark",
  "I know it’s still not good enough, but have an extra 1 minute 57 seconds of daylight",
  "I know things are still hard, but take things one day at a time and we can get through this together",
  "I love you, so I got you 2 minutes and 13 seconds extra daylight",
  "I'm not going to pretend it is",
  "I'm proud of you",
  "I'm so proud of you for making it this far",
  "I'm so proud of you, this was the hardest part",
  "I’m back, and I’m gonna get you through the darkness until the clocks change",
  "I’m proud of you",
  "I’m so proud of you",
  "If it helps, today the sun will set at 5.08pm, 6 minutes later than it did this day last week",
  "If just 10 days the day's got 17 minutes longer",
  "If you can, get out in the daylight and recharge your batteries, even if it's not sunny",
  "In 14 days you've added 14 minutes to sunset, and today adds another to 5.18pm",
  "In fact you've gained 3 whole minutes of daylight just in the last 5 days",
  "In fact, at 9 hours and 45 minutes of daylight, this is the longest the day's been since December 1",
  "In fact, in the last week you've added 6 whole minutes of daylight, and that's going to keep getting bigger every day",
  "In just 14 days, sunset has moved forward by 14 minutes",
  "In just 5 days you've got 7 minutes of extra daylight",
  "In just 7 days you've added 10 minutes of daylight",
  "In just the last 14 days, we've added 33 minutes of daylight, making today 11 hours and 25 minutes long",
  "In the last 10 days, we've added 20 minutes of daylight to the day",
  "In the last 14 days alone the day has got 32 minutes longer",
  "In the last 2 weeks we've added 20 whole minutes of daylight",
  "In the last 2 weeks you've added a whole 10 minutes of daylight to the day",
  "In the last 30 days we've added a whole 40 minutes of daylight, which is a really substantial jump",
  "In the last 7 days we've added more than 13 minutes of daylight",
  "In the meantime, have 2 minutes and 16 seconds extra daylight",
  "In your literal and metaphorical darkest hours, I will be there",
  "It gets better faster now",
  "It hasn’t been that early since November 25th",
  "It took just 6 days to add 10 minutes of daylight",
  "It was 1 minute and 51 seconds longer than yesterday",
  "It was 2 minutes and 21 seconds longer than yesterday, too",
  "It was 7.22am",
  "It was a double day, too: sunrise back to 7.19am, sunset forward to 5.24pm",
  "It was a double day: sunrise moved back to 7.16am, sunset moved forward to 5.28pm, and it took just 6 days to add a whole 10 minutes to the length of the day -- it was 10 hours and 12 minutes long",
  "It was a double day: sunrise moved back to 7.17am, and sunset forward to 5.27pm",
  "It was a struggle, and I'm proud of you",
  "It was a triple day: sunrise went back 2 minutes to 6.35am, sunset forward to 6.07pm, and today was 11 and a half hours long",
  "It was at 5.33pm, and congratulations: you made it through January",
  "It was incredibly hard and you should recognize it as a real accomplishment",
  "It was less than a second of extra daylight, but the longer is better than shorter, and every day will get more daylight, in larger amounts each day, all the way to summer",
  "It wasn't all bad: in February we added 30 minutes to sunset and 62 minutes of extra daylight, with 2 minutes and 23 seconds of precious extra daylight arriving today",
  "It's a double day as usual, with sunrise going back to 7.02am and sunset forward to 5.48pm, with 2 minutes and 13 seconds of extra daylight",
  "It's a mini milestone today too: sunrise has reached 7am",
  "It's a second",
  "It's a short month and we're gonna zip through it",
  "It's also the first day we added more than 2 whole minutes of daylight",
  "It's awful, but it's also a full 10 minutes later than the worst, which was 4.50pm",
  "It's funny how the minutes jump around unpredictably, but it's feeling better all the time",
  "It's nice",
  "It's no longer crushing",
  "It's not a round number or anything, but it really feels like progress",
  "It's not good",
  "It's not great, but we can deal",
  "It's really piling up now",
  "It's the first 10-hour day of the year, and a full 28 minutes more daylight than the solstice",
  "It's the last dark day",
  "It's the last day the sun sets before 5pm",
  "It's the milestone you've been waiting for: today the sun set at 6pm",
  "It's the shortest month and we're gonna get through it together",
  "It's yet another double day: sunrise back to 7.13am, sunset forward to 5.35pm",
  "It’ll be okay",
  "It’s 11 and a half hours long, which is the longest day since the 7th of October",
  "It’s a long road, but we can make it",
  "It’s also the Orthodox New Year in some places, apparently",
  "It’s gonna be okay",
  "It’s just a trick of the clock, but that’s a minute later than it was yesterday",
  "It’s not great, but it’s definitely better",
  "It’s still dark too soon, but we can do this",
  "It’s the first 11-hour day of the year",
  "January is 10% over already",
  "January is over",
  "January is the worst, and you killed it",
  "January’s nearly over",
  "Just 15 more to go, we’ll be at 6pm soon",
  "Just since January 1st you've gained 24 minutes of daylight",
  "Just today you got 1 minute and 34 seconds extra",
  "Kiss February goodbye",
  "Let's do this",
  "Let's kick off strong with a double day: sunrise back to 7.14am, sunset forward to 5.34pm",
  "Longest day since October 13th",
  "Milestone coming up tomorrow, stay with me",
  "Milestone tomorrow",
  "Monday",
  "More and more every day",
  "More every day",
  "My cat’s breath smells like cat food",
  "Nearly okay",
  "Nearly to 5pm",
  "Nearly two minutes",
  "Nice",
  "Not a bad Wednesday",
  "Not a huge milestone or anything, just another delightful 2 minutes and 24 seconds of extra daylight to brighten your day",
  "Not too shabby",
  "Obviously 5pm is still no good, but today was 26 seconds longer than yesterday as well",
  "October wasn’t too bad, right? And it’s getting better still",
  "Oh, we’ve got this",
  "On top of that, it was our first *triple* day: sunrise moved back 1 minute to 7.20am, and sunset moved forward *2* minutes to 5.22pm",
  "One breath at a time, we’ll get there",
  "One full, precious minute of daylight, and every day more",
  "Only 10 more minutes to gain until 6pm",
  "Onward to February",
  "Our first 11-hour day",
  "Our first 5.30 sunset of the year",
  "Our gains are going to keep accelerating, thanks to the magic of orbital mechanics",
  "Plus 47 seconds more daylight",
  "Plus it's a double day",
  "Plus the day was 10 hours and 53 minutes long, which means that day had 1 hour and 17 minutes more daylight than the solstice did",
  "Plus you got 1 minute and 27 seconds of extra daylight, just today",
  "Plus you got 1 minute and 39 seconds of extra daylight",
  "Plus you got 1 minute and 4 seconds extra daylight",
  "Plus you got 2 minutes and 11 seconds of extra daylight",
  "Plus you got 2 minutes and 5 seconds of extra daylight",
  "Plus you got a minute and 12 seconds of extra daylight",
  "Plus you got a whole 1 minute and 56 seconds of extra daylight",
  "Plus, today you got 21 extra seconds of daylight",
  "Plus, tomorrow is a milestone day, so look forward to it",
  "Plus, tomorrow is Friday",
  "Pretty decent",
  "Progress has been so slow so far, but now it really picks up",
  "Progress",
  "Put that pesky 2016 behind you with an extra 40 seconds of daylight",
  "Real progress",
  "Savor every second, this is going to be okay",
  "Savor it",
  "Savor the extra light",
  "Savor them",
  "See you next January",
  "See you next year",
  "See you then",
  "Since the solstice the day has got more than 24 minutes more daylight",
  "Since the solstice you've added a whole 8 minutes to sunset time",
  "Sit for 42 seconds and think how long that is",
  "Slowly at first, but we can make it",
  "So close",
  "So in the last 7 days, we've added 8 minutes of daylight",
  "So much, so fast",
  "So much",
  "So stay strong and I'll see you then",
  "Sorry for the gap",
  "Starting tomorrow, every day will be longer than the last, and the days will get longer by more each day",
  "Starting tomorrow, sunrise starts moving backwards, too",
  "Stay with me, you can do this",
  "Stick to your guns this week; Thursday’s a milestone",
  "Stick with me, tomorrow is our next mini milestone",
  "Stick with me",
  "Still accelerating",
  "Sunrise and sunset don’t move at the same speed",
  "Sunrise continues to fly backwards to 7.07am, and sunset skipped forward 2 minutes to 5.41pm, with 2 minutes and 7 seconds of extra precious daylight",
  "Sunrise has been creeping backwards too; it was at 7.20am today, 5 minutes earlier than Jan 1.",
  "Sunrise has gone back another 5 minutes to 7.15, too",
  "Sunrise has slipped back to 7.20am",
  "Sunrise has stopped getting later, too",
  "Sunrise is 2 minutes back to 6.37am, sunset 1 minute forward to 6.07pm, and another mini-milestone: today was 11.5 hours long",
  "Sunrise is all the way back to 6.41am",
  "Sunrise is all the way back to 7.01am, sunset forward all the way to 5.49pm, this is like it was back on October 26th last year",
  "Sunrise is back to 6.56am, sunset has got as far as 5.51pm",
  "Sunrise is back to 7.20am, sunset is up to 5.24pm",
  "Sunrise is going to start moving backwards pretty quickly, so double days are going to get more common",
  "Sunrise moved all the way back to 7am, which if you ask me is a fine time for the sun to rise",
  "Sunrise moved back by a minute to 7.02am, too",
  "Sunrise moved back to 6.48am, sunset forward to 5.58pm, and the day was 11 hours and 10 minutes long",
  "Sunrise moved back to 6.49am, and sunset forward to 5.57pm",
  "Sunrise moved back to 6.58am, sunset forward to 5.49pm",
  "Sunrise moved back to 7.06am and sunset forward to 5.42pm",
  "Sunrise moved back to 7.09am, sunset moved forward to 5.38pm, and today's mini milestone is that today was 10 and a half hours long",
  "Sunrise moved back to 7.10am, and sunset forward to 5.37pm, which is really beginning to feel okay",
  "Sunrise moved back to 7.11am, sunset forward to 5.35pm, and we've hit our milestone: today had a whole 2 minutes more daylight than yesterday",
  "Sunrise moved back to 7.15am, which is honestly fine, and sunset moved forward to our mini milestone: 5.30pm",
  "Sunrise moved back to 7.18am, sunset moved forward to 5.25pm, and you got 1 minute and 44 seconds of extra daylight, which is really quite a lot to be adding every day",
  "Sunrise moved back to 7.19am, sunset moved forward to 5.24pm, and there was 1 minute and 42 seconds of extra daylight",
  "Sunrise moved back to 7.22am and sunset forward to 5.21pm",
  "Sunrise moved back to 7.22am, sunrise moved forward to 5.17pm",
  "Sunrise moved backwards 1 minute to 6.52am, but sunset moved forward 2 minutes to 5.55pm",
  "Sunrise moved backwards 1 minute to 7.01am, and sunset forward 1 minute to 5.46pm",
  "Sunrise moved backwards by 1 minute to 7.25am, while sunset moved forward to 5.12pm",
  "Sunrise moved backwards to 7.21am, sunset moved forwards to 5.19pm, and another whole 1 minute and 33 seconds of daylight was yours to enjoy",
  "Sunrise moved backwards to 7.23am, and sunset moved forwards to 5.14pm, plus you got 1 minute and 20 seconds of extra daylight",
  "Sunrise moved backwards, too",
  "Sunrise ticked back to 7.22am, sunset forward to 5.19pm",
  "Sunrise ticked back to 7.24am and sunset forward to to 5.15pm",
  "Sunrise today was 6.59am, which is honestly kind of early? Sunset was at 5.51pm, which is still too early, but so much better",
  "Sunrise was 6.39am, sunset was 6.06pm, and you got 2 minutes and 24 seconds of extra daylight",
  "Sunrise was 7.16am, sunset was 5.28pm, and you got 1 minute and 50 seconds of extra daylight",
  "Sunrise was also a minute earlier than yesterday, at 7.24am",
  "Sunrise was at 6.33am, sunset was at 6.10pm, and those are fine but JUST WAIT until tomorrow",
  "Sunrise was at 7am",
  "Sunrise went back 1 minute to 6.37am, sunset forward to 6.06pm, and soon things will be good",
  "Sunrise went back 1 minute to 6.42am, sunset forward 1 minute to 6.04pm",
  "Sunrise went back 1 minute to 6.54am and sunset forward 1 minute to 5.55pm",
  "Sunrise went back 1 minute to 7.05am, and sunset went forward a minute to 5.43pm, which is really beginning to feel okay, especially since today was 10 hours and 38 minutes long",
  "Sunrise went back 1 minute to 7.24am, and sunset kept moving forward, to 5.10pm",
  "Sunrise went back 2 minutes to 6.39am, and sunset forward to 6.04pm",
  "Sunrise went back 2 minutes to 6.40am, and sunset went forward 1 minute to 6.05pm",
  "Sunrise went back 2 minutes to 6.44am, and sunset was at a totally manageable 6.02pm",
  "Sunrise went back a minute to 6.59am, and sunset moved forward 1 minute to 5.48pm",
  "Sunrise went back to 6.31am, and sunset forward to 6.10pm, with yet another 2 minutes and 25 seconds of extra daylight",
  "Sunrise went back to 6.43am, and sunset moved forward to 6.01pm",
  "Sunrise went back to 6.53am, and sunset went forward to 5.53pm",
  "Sunrise went back to 7.03am, and sunset forward to 5.47pm",
  "Sunrise went back to 7.06am and sunset forward to 5.44pm",
  "Sunrise went back to 7.07am and sunset forward to 5.43pm",
  "Sunrise went back to 7.08am, sunset went forward to 5.42pm, and 2 minutes and 7 seconds of extra daylight showed up",
  "Sunrise went back to 7.08am, which is pretty early to be honest, and sunset forward to 5.39pm",
  "Sunrise went back to 7.09am and sunset forward to 5.41pm",
  "Sunrise went back to 7.10am and sunset forward to 5.40pm, which is almost an okay time",
  "Sunrise went back to 7.11am, and sunset forward to 5.39pm",
  "Sunrise went back to 7.12am today, and sunset forward to 5.34pm",
  "Sunrise went back to 7.17am, which is the earliest it’s been since December 14th",
  "Sunrise went back to 7.18am and sunset forward to 5.28pm, after 1 minute and 48 seconds of extra daylight",
  "Sunrise went back to 7.18am, and sunset forward to 5.29pm",
  "Sunrise went back to 7.19am, and sunset forward to 5.27pm",
  "Sunrise went back to 7.20am and sunset forward to 5.25pm, which is a whole 30 minutes later than it was on the solstice",
  "Sunrise went back to 7.20am, which is fine, and sunset forward to 5.25pm, which is a little less than fine but okay",
  "Sunrise went back to 7.21am and sunset went forward to 5.23pm",
  "Sunrise went back to 7.23am and sunset forward to 5.18pm, after nearly a minute and a half more daylight than just yesterday",
  "Sunrise went back to 7.24am, and sunset went forward to 5.16pm",
  "Sunrise went backwards 1 minute to 7.12am, sunset jumped forwards 2 minutes to 5.37pm",
  "Sunrise went backwards by 2 minutes to 7.07am, which is honestly fine, and sunset forward to 5.42pm",
  "Sunrise went backwards to 7.19am, sunset forwards to 5.26pm",
  "Sunrise went backwards to 7.22am, sunset went forwards to 5.21pm",
  "Sunrise went backwards to 7.23am, sunset forward to 5.19pm, with 1 minute and 29 seconds of extra daylight",
  "Sunset also moved forward to 5.47pm, and you got 2 minutes and 13 seconds of extra daylight",
  "Sunset at 5.23pm",
  "Sunset got vanquished yet again, moving forward to 5.17pm after 1 minute and 26 seconds of extra daylight, just today",
  "Sunset has moved 32 minutes forward in just the last 30 days",
  "Sunset is a full 4 minutes later than it was that day, and tomorrow is a little mini-milestone",
  "Sunset is after 7pm tomorrow",
  "Sunset is already 3 minutes later than when we started",
  "Sunset is now 18 minutes later than the start of the year",
  "Sunset is shifting quickly, and was at 4.58pm today",
  "Sunset moved back by a minute to 5.21pm, too",
  "Sunset moved back to 5.15pm",
  "Sunset moved back to 5.22pm",
  "Sunset moved back to 6.09pm, which is pretty good, sunrise moved back 2 minutes to 6.32am, and today was 11 hours and 39 minutes long, which is an hour longer than Feb 10 was and more than 2 hours longer than the solstice was back in December",
  "Sunset moved forward 1 minute to 5.12pm",
  "Sunset moved forward 5.04pm",
  "Sunset moved forward by a minute to 5.08pm and you got 58 seconds of extra daylight: nearly a whole minute in a single day",
  "Sunset moved forward to 5.05pm, too",
  "Sunset moved forward to 5.09pm",
  "Sunset moved forward to 5.10pm",
  "Sunset moved forward to 5.16am, sunrise moved back to 7.23am",
  "Sunset moved forward to 5.16pm",
  "Sunset moved forward to 5.18pm to fit all that extra daylight in",
  "Sunset moved forward to 5.19pm, sunrise moved back to 7.22am",
  "Sunset moved forward to 5.19pm, too",
  "Sunset moved forward to 5.23pm and there was a whole 1 minute and 40 seconds of extra daylight today, meaning today was a full 30 minutes longer than the solstice was",
  "Sunset moved forward to 5.24pm",
  "Sunset moved forward to 5.26pm, and you got 1 minute and 47 seconds of extra daylight today",
  "Sunset moved forward to 5.26pm",
  "Sunset moved forward to 5.28pm, and sunrise keeps moving back and has got to 7.17am",
  "Sunset moved forward to 5.31pm, meaning in 30 days it's moved 30 minutes",
  "Sunset moved forward to 5.52pm, and tomorrow's another milestone, so stay with me",
  "Sunset pushed forward again to 5.09pm",
  "Sunset ticked forward 1 more minute to 5.01pm and you got 36 extra seconds of daylight",
  "Sunset ticked forward another 1 minute to 5.01pm, and you got a whole 31 extra seconds of daylight just today, meaning you've added a whole minute of daylight in just 2 days",
  "Sunset ticked forward another minute to 5.02pm",
  "Sunset ticked forward another minute to 5.10pm, which is a whole 15 minutes later than the solstice was",
  "Sunset ticked forward by 1 minute to 5.04pm today, and it's a mini milestone: sunset will move forward by at least 1 extra minute every day from here on",
  "Sunset ticked forward by 1 minute today",
  "Sunset ticked forward by a minute to 5.03pm and there were 41 seconds of extra daylight today",
  "Sunset ticked forward by another minute today, to 4.57pm, and today was 10 seconds longer than yesterday, so you've already gained 19 seconds since the solstice",
  "Sunset ticked forward to 5.01pm",
  "Sunset ticked forward to 5.02pm",
  "Sunset ticked forward to 5.09pm and you got 1 minute and 3 seconds of extra daylight",
  "Sunset ticked forward to 5.12pm, and tomorrow is a mini milestone, so look forward to it",
  "Sunset ticked forward to 5.17pm, sunrise ticked back to 7.23am",
  "Sunset ticked forward to 5pm today, and you also got a full 27 seconds of extra daylight",
  "Sunset ticked forward yet again, to 5.02pm, and there were a full 34 seconds of extra daylight today for a total of 3 whole minutes of pure, joyful daylight since the solstice",
  "Sunset ticked over to 5.01pm, which is 6 minutes later than the solstice",
  "Sunset time ticked over again, to 4:56PM today",
  "Sunset today was 13 minutes later than Jan 1. By the end of Jan it'll add 30 mins",
  "Sunset today was at 4.55pm",
  "Sunset was 5.57pm",
  "Sunset was at 4:58PM, too",
  "Sunset was at 5.02pm",
  "Sunset was at 5.07pm",
  "Sunset was at 5.10pm, 1 minute later than yesterday",
  "Sunset was at 5.10pm",
  "Sunset was at 5.12pm, 10 minutes longer than on the first of January",
  "Sunset was at 5.13pm — five minutes gained since last week",
  "Sunset was at 5.14pm",
  "Sunset was at 5.15pm, which is 15 minutes later than it was on January 1.",
  "Sunset was at 5.26pm",
  "Sunset was at 5.27pm",
  "Sunset was at 5.31pm",
  "Sunset was at 5.34pm, 32 whole minutes later than January 1",
  "Sunset was at 5.40pm, which is close to being acceptable",
  "Sunset was at 5.40pm",
  "Sunset was at 5.42pm today, which is a whole half hour later than January 13th",
  "Sunset was at 5.42pm",
  "Sunset was at 5.44pm",
  "Sunset was at 5.49pm, which is not good enough yet",
  "Sunset was at 5.49pm",
  "Sunset was at 5.50pm today",
  "Sunset was at 5.50pm",
  "Sunset was at 5.54pm",
  "Sunset was at 5.56pm",
  "Sunset was at 5PM today",
  "Sunset was at 6.01pm",
  "Sunset was at 6.02pm and today was 11 hours and 19 minutes long",
  "Sunset was at 6.02pm",
  "Sunset was at 6.03pm today, which is totally fine",
  "Sunset was at 6.04pm today",
  "Sunset was at 6.04pm, and the day was 11 hours and 24 minutes long",
  "Sunset was at 6.07pm",
  "Sunset was at 6.08pm",
  "Sunset was at 6.09pm today and tomorrow is going to be FANTASTIC",
  "Sunset was at 6.09pm",
  "Sunset was at 6.12pm today",
  "Sunset was at 6.12pm",
  "Sunset was at 6pm today",
  "Sunset was at 7:16pm today and the terrible days of winter are over",
  "Sunset was at 7.10pm today, and the horrible, dark nights of winter are over",
  "Sunset was at 7.11 today — the horrible, dark days of winter are OVER",
  "Sunset was at 7.13pm today",
  "Sunset was now at 5.05pm, and 47 seconds of extra daylight mean in two weeks you've accumulated 6 minutes of extra daylight",
  "Sunset was now at 5.06pm, and you also got 51 extra seconds of daylight today",
  "Sunset wasn’t until 5.35pm",
  "Sunset wasn’t until 5.55pm",
  "Sunset wasn’t until 6.04pm",
  "Sunset wasn’t until 6.07pm today, I hope you found some sunshine this Sunday",
  "Sunset wasn’t until 6.10pm",
  "Sunset went forward to 5.24pm, which is, like, early, but not so early it feels terrible anymore, right?",
  "Sunset went forward to 5.27pm",
  "Sunset went forward to 5.31pm, and there was 1 minute and 54 seconds of extra daylight",
  "Sunset went forward to 5.36pm",
  "Sure, it’s just a number, but it’s still nice",
  "Take a breath",
  "Take a deep breath and let it out: that much more daylight",
  "Take a long breath, it was that much more",
  "Take heart, my friends",
  "Take that deep breath now",
  "That hasn't happened since the clocks changed back in November",
  "That hasn’t happened since November 3rd",
  "That last 30 minutes all arrived since February 20th",
  "That may suck, but take heart: since the solstice sunset has ticked forward by 11 minutes, including 1 extra minute today",
  "That means today is our first double-day: sunrise and sunset both moved, with sunset at 5.13pm",
  "That much extra",
  "That's 20 minutes later than on the solstice",
  "That's 21 minutes later than the earliest sunset was, back in December",
  "That's 26 minutes longer than the solstice day was",
  "That's 3 minutes in 3 days",
  "That's a decent amount in a pretty short time, and it's getting fast all the time",
  "That's a full 30 minutes later than the start of the month",
  "That's a lot of day",
  "That's a lot",
  "That's a real difference",
  "That's a whole 20 minutes later than just 2 weeks ago",
  "That's already 3 clock minutes later than the sunset was on the solstice",
  "That's bearable",
  "That's beginning to feel like a nearly acceptable time, and we're nearly through January",
  "That's beginning to seem like a decent time for a sunset, right? Nearly 5.30. Not so horrible",
  "That's good going",
  "That's how we're going to get there: one tiny step at a time",
  "That's huge",
  "That's like a proper day, not a horrible day",
  "That's more than 11 minutes just since last Thursday",
  "That's nice",
  "That's not bad",
  "That's noticeable",
  "That's real and solid and you can hold on to it",
  "That's really going to start pushing the day out",
  "That's so much time",
  "That's some real progress",
  "That's still horribly early, but it's 5 minutes later than the solstice",
  "That's two whole minutes extra since the solstice, and it'll be at least half a minute every day from now on",
  "That’s 10 minutes in 10 days, and it will keep getting faster",
  "That’s 11 minutes later than the solstice",
  "That’s 20 minutes more than you did on the solstice, and 83 seconds more than yesterday",
  "That’s 24 minutes longer than January 1 was",
  "That’s 5 minutes since last Tuesday",
  "That’s a lot",
  "That’s a whole extra hour since February 10th",
  "That’s a whole hour later than it was on December 31st",
  "That’s actually pretty early",
  "That’s beginning to feel okay",
  "That’s beginning to seem like a decent day",
  "That’s decent",
  "That’s gotta feel good",
  "That’s nearly decent",
  "That’s nice, right?",
  "That’s nice",
  "That’s not a bad day",
  "That’s not good enough, but it’s 10 minutes later than the earliest sunset was",
  "That’s not good enough, but we’ll get there together",
  "That’s okay",
  "That’s practically done",
  "That’s still awfully early, but it’s 6 minutes later than at the solstice",
  "That’s the first of those since way back on October 21 last year",
  "The 2 minutes and 3 seconds of extra daylight are really helping; today was 54 minutes longer than the solstice was",
  "The clock ticked over again, and sunset was at 4.57pm today",
  "The clocks change this month",
  "The darkest days of winter are over",
  "The day had 2 minutes and 17 seconds more daylight",
  "The day hasn't been this long since November 20th last year",
  "The day is more than 6 minutes longer than it was just 3 days ago, because you got an extra 2 minutes and 8 seconds of daylight today",
  "The day was 10 hours and 20 minutes long",
  "The day was 10 hours and 26 minutes long today, 2 minutes and 3 seconds more daylight than just yesterday",
  "The day was 10 hours and 51 minutes long, which makes it a whole hour longer than January 15th was",
  "The day was 10 hours and 7 minutes long, which is not bad, but it's getting a lot better a lot faster now, so hang on",
  "The day was only 3 seconds longer, so it's mostly a trick of the clock, but 3 seconds is 3 seconds",
  "The days are short but they will get longer, steadily, every day, and I'll be here to get you through it",
  "The end of the final dark week",
  "The extra time added is getting bigger, faster every day",
  "The final crappy sunset",
  "The horrible, dark days of winter are OVER",
  "The last 10 hour day was all the way back on November 19th",
  "The last 10 hour day wasn’t since November 19th",
  "The last dark day",
  "The last time that happened was way back on November 20th last year",
  "The only good thing about it is: this is as bad as it gets",
  "The sun didn’t set until 5.30pm today",
  "The sun didn’t set until 5.36.",
  "The sun didn’t set until 5.54pm",
  "The sun didn’t set until 6.04pm",
  "The sun set after 5pm today for the first time since November 13th",
  "The sun set after 6pm today for the first time since November 1",
  "The sun set at 4.55pm today, which is no kind of time",
  "The sun set at 4.56pm today, 9 seconds later than yesterday",
  "The sun set at 4.57pm today, and there were 13 seconds more daylight",
  "The sun set at 5:02pm today, 37 seconds more daylight than yesterday",
  "The sun set at 5.06pm today, which is the latest sunset since November 5th",
  "The sun set at 5.07pm, a minute forward from yesterday",
  "The sun set at 5.20pm",
  "The sun set at 5.22.",
  "The sun set at 5.24.",
  "The sun set at 5.25.",
  "The sun set at 5.34.",
  "The sun set at 5.35.",
  "The sun set at 5.38.",
  "The sun set at 5.40.",
  "The sun set at 5.40pm, which is nearly okay",
  "The sun set at 5.42.",
  "The sun set at 5.43.",
  "The sun set at 5.43pm",
  "The sun set at 5.47.",
  "The sun set at 5.47pm",
  "The sun set at 5.51pm",
  "The sun set at 5.58.",
  "The sun set at 5.58pm",
  "The sun set at 5pm today, for the first time since November 12",
  "The sun set at 5pm today",
  "The sun set at 6.01.",
  "The sun set at 6.03pm today, and today was 2 minutes and 23 seconds longer than yesterday",
  "The sun set at 6.04.",
  "The sun set at 6.06.",
  "The sun set at 6.11.",
  "The sun set moved forward to 5.50pm, which means the sunset a whole hour later than it did on the solstice, back in December",
  "The sun setting before 5pm still isn't good, but we're going to get there",
  "The sun’s gift to you is 13 seconds of precious extra daylight",
  "The sunset ticked forward again today, to 4.56pm",
  "The time will tick up by at least a minute every day from now on",
  "The toughest days are behind us",
  "The two worst months of early darkness are behind you",
  "The week is almost over, and you had 2 minutes and 25 seconds more daylight",
  "The whole day had 9 hours and 48 minutes of daylight in it",
  "The worst of February is over, everybody",
  "There are 10 whole hours of daylight today, so step outside and enjoy them",
  "There are microwave meals that take less time than that to prepare",
  "There hasn't been a day this long since last November 19th",
  "There hasn't been a day this long since October 20th last year",
  "There hasn't been a day this long since the 8th of November",
  "There hasn't been an 11-hour day since October 20th, so we're really climbing back to good",
  "There hasn’t been a ten-hour day since November 19th",
  "There was 1 minute and 47 seconds of extra daylight, and sunset was at 5.28pm",
  "There were 10 hours and 57 minutes of daylight today, and that got longer by 2 minutes and 17 seconds just today",
  "There were 17 seconds of extra daylight today",
  "There were 2 minutes and 6 seconds of extra daylight and it's really beginning to feel like a proper day again",
  "There were 28 extra seconds of daylight",
  "There were 9 whole seconds of extra daylight today, and sunset ticked over another minute boundary to 4.57pm",
  "There were a whole 50 seconds of extra daylight today, which means we've added 5 minutes of daylight in just the last 8 days",
  "There were only 2 seconds of extra daylight, but that was enough to step over the boundary between minutes",
  "There’s a big milestone this week, so keep holding on",
  "There’s only 28 days and we are gonna make it through",
  "Things are gonna be okay",
  "Things are nearly okay",
  "Things start getting better much faster now",
  "Think about 2 minutes of extra sunlight on your face",
  "This is also the last day the sun will set before 5pm",
  "This is as bad as it gets, and let's be honest, it's shit",
  "This is beginning to be okay",
  "This is beginning to feel not terrible",
  "This is beginning to feel okay",
  "This is getting faster",
  "This is going to be okay",
  "This is gonna be okay",
  "This is great",
  "This is hard, but I’m here for you",
  "This is not bad at all",
  "This is really beginning to be okay",
  "This is the final week of dark days",
  "This is the first 10-hour day since November 21st 2011",
  "This is the last dark Thursday of 2017. You can make it to the end of the year, it’s so close",
  "This is the last day it sets before 5pm, and I know you can make it",
  "This is the last time it will set before 5pm",
  "This isn’t good enough yet, but it’s not horrible",
  "This starts going faster now",
  "This Sunday had 14 minutes more daylight than last Sunday did",
  "This Thursday is the solstice, and I’ll be back to help you get through it with a cheerful reminder of the little ways things get better",
  "This time it's sunrise moving 2 minutes back to 6.50am, and sunset moved forward 1 minute to 5.56pm, with 2 minutes and 19 seconds of extra daylight",
  "This weekend is the weekend the magic happens",
  "Those are totally bearable",
  "Three cheerful things: you've only got 1 more day left of what was probably a short work week, sunset moved forward to 5.03pm, and you got 43 extra seconds of daylight",
  "Time changes are confusing",
  "To a new year, and new sunrises",
  "To celebrate, have 37 whole extra seconds of daylight today",
  "To celebrate, have a double day: sunrise went back to 7.15am, and sunset forward to 5.33pm",
  "To celebrate, have a double day: sunrise went back to 7.16am, sunset went forward to 5.32pm, and there was 1 minute and 54 seconds of extra daylight today",
  "To celebrate, it's a *triple* day: sunrise went back to 7.14am, and sunset skipped forward 2 minutes to 5.32pm",
  "To celebrate, we knocked 2 minutes off sunrise to 6.34am, and added a minute to sunset to 6.09pm, plus 2 minutes and 25 seconds of extra daylight",
  "To get you there, have 1 minute and 21 seconds extra daylight",
  "To kick off, have a double day: sunrise moved back to 7.13am and sunset moved forward to 5.33pm",
  "To kick off, sunrise went back 1 minute to 6.50am and sunset forward 1 minute to 5.58pm",
  "To kick things off, it's a double day: sunrise was 7.15am, sunset was 5.33pm",
  "To see you off into the glorious long summer nights, it was a triple day: sunrise went back 2 minutes to 6.29am, sunset forward to 6.11pm",
  "Today also had a full 30 seconds of extra daylight",
  "Today also had a whole 1 minute and 23 seconds of extra daylight",
  "Today for the first time you got more than a minute of extra daylight: 1 minute and 1 second, to be exact, and we should be exact, because every extra second of daylight is precious",
  "Today had 1 minute and 4 seconds of extra daylight",
  "Today had a full hour more daylight that the first of February did",
  "Today had a whole 1 minute and 51 seconds of extra daylight",
  "Today had a whole 47 minutes more daylight than 30 days ago",
  "Today had almost 30 seconds more daylight than the darkest day had",
  "Today is the first day sunset moves by *two* minutes -- jumping straight to 5.20pm after 1 minute and 31 seconds of extra daylight",
  "Today is the first day you get a full extra minute of daylight, and from now on, every single day, sunset will tick forward by at least 1 minute per day",
  "Today sunset ticked forward not by 1 minute but by *2* minutes",
  "Today sunset went forward by 1 minute to 5.40pm, and it's a mini milestone: from tomorrow onwards, every single day is a double day, and some are triple days",
  "Today that reversed",
  "Today the day had 10 whole hours of daylight",
  "Today the sun set at 4.57, which is 3 minutes later than it did on the solstice",
  "Today there were 10 whole hours of daylight",
  "Today there were 8 seconds more daylight than yesterday",
  "Today was 1 minute and 53 seconds longer than yesterday, too",
  "Today was 10 hours and 19 minutes long",
  "Today was 10 hours and 20 minutes long, the longest day since November 8th",
  "Today was 10 hours and 32 minutes long, the first 10 and a half hour day since November 2nd, 2020, which seems a million years ago now",
  "Today was 10 hours and 33 minutes long, courtesy of another 2 minutes and 6 seconds of daylight",
  "Today was 10 hours and 46 minutes long",
  "Today was 10 hours long",
  "Today was 10 minutes longer than the solstice was",
  "Today was 11 hours and 24 minutes long, which is the longest day there's been since October 11th last year",
  "Today was 11 hours and 26 minutes long, which is pretty good",
  "Today was 11 hours and 31 minutes long, the longest since October 7.",
  "Today was 11 whole hours long, thanks to 2 minutes and 18 seconds of extra daylight",
  "Today was 12 whole minutes longer than last Friday was, that’s how fast we’re racking up daylight now",
  "Today was 13 seconds longer than yesterday",
  "Today was 17 minutes longer than last Wednesday",
  "Today was 1m45s longer than yesterday",
  "Today was 2 minutes and 19 seconds longer than yesterday",
  "Today was 30 minutes longer than the 1st of January was",
  "Today was 9 hours and 38 minutes long, which is more than 5 minutes of extra daylight since the solstice",
  "Today was a double day, sunrise moved back to 7.12am and sunset forward to 5.34pm",
  "Today was another 2 minutes and 26 seconds longer than yesterday",
  "Today was more than 10 and a half hours long, the longest day since November 4th last year",
  "Today was nearly 3 minutes longer than December 21st was",
  "Today was one whole minute longer than yesterday",
  "Today was our first *triple* day: sunrise went back to 7.17am, and sunset forward by 2 minutes to 5.30pm",
  "Today was the first 11 hour day since all the way back in October",
  "Today was very slightly longer than yesterday",
  "Today was yet another double day, with sunrise going backwards to 7.10am and sunset to 5.39pm",
  "Today we added 2 minutes and 15 seconds, just today",
  "Today you got 2 minutes and 21 seconds of extra daylight",
  "Today's a mini milestone: the day was 5 minutes longer than the solstice",
  "Today's a triple day -- sunrise went back to 6.42am, and sunset forward to 6.02pm",
  "Today's a triple day: sunrise went back by 2 minutes again to 6.52am, and sunset forward to 5.56pm",
  "Today's mini milestone is that today is our first Double Day: sunset moved forward to 5.10pm, and sunrise moved back to 7.24am",
  "Today's sunrise was 6.51am and sunset was 5.57pm, a minute further in both directions",
  "Today's the first day you got more than a minute and a half of extra daylight: 1 minute and 32 seconds more",
  "Tomorrow I will start tweeting every day about how much extra daylight there is every day until the clocks change",
  "Tomorrow is a little milestone, stay with me",
  "Tomorrow is a MAJOR milestone, so get hyped",
  "Tomorrow is a major milestone",
  "Tomorrow is a milestone",
  "Tomorrow is our next mini milestone",
  "Tomorrow is the solstice, so tomorrow we begin",
  "Tomorrow something new and good starts happening",
  "Tomorrow we reach our next mini milestone, so don't go anywhere",
  "Tomorrow will be 55 seconds longer than today",
  "Tomorrow will be another 1m10s longer still",
  "Tomorrow will have twice that many",
  "Tomorrow, there will be 3 extra breaths of daylight",
  "Tomorrow: 10 hours",
  "Tomorrow's a big milestone",
  "Tomorrow's a fun milestone",
  "Tomorrow's a milestone day",
  "Tomorrow's a milestone, so look forward to it",
  "Tomorrow's a mini milestone (you can probably guess what it is",
  "Tomorrow's a mini milestone, so look forward to it",
  "Tomorrow's a mini milestone, so stay tuned",
  "Tomorrow's a mini milestone",
  "Tomorrow’s a big milestone",
  "Tomorrow’s a little milestone",
  "Tomorrow’s a really nice milestone",
  "Tonight the clocks go back by 1 hour",
  "Tonight the clocks go forward, and the sun will set after 7pm tomorrow",
  "Twice as many seconds longer than yesterday",
  "Until today, sunrise was also moving forward, but as of today it stops, and soon it will start moving backwards as well as the days get longer faster",
  "Until today, sunrise was getting later, but now it starts getting earlier, too",
  "Until today, while sunset has been moving forwards, sun*rise* has also been moving later",
  "Until today, while sunset was moving forwards, sunrise was also moving forwards, but today that changes and sunrise starts moving backwards, so the day is getting longer at both ends",
  "Use ‘em or lose 'em",
  "We added only 5 more seconds of daylight, but that was 500% more extra daylight than yesterday",
  "We added those 3 minutes and 22 seconds just since Sunday",
  "We are going to be okay",
  "We are going to get through this together, you and me",
  "We are going to make it",
  "We can all agree that the sun setting before 5pm is bullshit, but that will end before the new year begins",
  "We can do it together",
  "We can do this, together",
  "We can do this, with 1 minute and 47 seconds extra daylight today",
  "We can make it to February",
  "We can make this",
  "We gained 2 minutes and 20 seconds",
  "We gained nearly as much daylight in one day today as we did in the first 3 days after the solstice",
  "We got there with 2 minutes and 6 seconds of extra daylight since yesterday",
  "We have got this",
  "We made it to 6pm sunset -- in fact, today's sunset is 6.01pm, and sunrise went back to 6.44am",
  "We made it to a 5.30pm sunset",
  "We made it",
  "We will get through this, together",
  "We're approaching some fun mini milestones soon, so don't give up",
  "We're creeping up on a milestone",
  "We're doing this",
  "We're going to get there",
  "We're gonna be packing on extra daylight even faster every day, so hang on",
  "We're gonna get there",
  "We've added 2.5 minutes to the total length of the day since the solstice",
  "We've added 5 minutes of daylight in just 6 days",
  "We've added a full 30 minutes of daylight since just 3 weeks ago, and tomorrow is a milestone",
  "We've got 10 minutes of extra daylight added in just the last 9 days",
  "We’re really adding serious daytime now",
  "We’re really chugging along now",
  "We’re so close to 6pm you can taste it",
  "We’ve added 10 minutes just since Feb 1",
  "We’ve added 10 minutes of daylight just since Saturday",
  "We’ve added 15 whole minutes of daylight to the day since the solstice, and the next 15 come fast",
  "We’ve added half an hour of daylight since just 2 weeks ago",
  "We’ve already gained six and a half minutes since solstice",
  "We’ve got January on the run",
  "What an excellent Saturday",
  "What can you do in 2 minutes and 14 seconds? Lots",
  "What can you do in 8 seconds? Maybe just sit and appreciate them",
  "What I know is that sunset ticked forward *another* minute to 4.58pm",
  "Whee",
  "You also got 51 extra seconds of daylight",
  "You and me are going to make it through to spring, together",
  "You are going to make it",
  "You are more than half-way through January",
  "You are more than halfway from the solstice to the time change",
  "You are really on the home stretch now",
  "You can do this, just stick with me",
  "You can feel it",
  "You can have a decent conversation in 41 seconds",
  "You can make it through January",
  "You can make it to the end of the year",
  "You can make this",
  "You can tell you're going to make it, now",
  "You could have a decent, sun-lit conversation in that time",
  "You did it",
  "You don't have to struggle all the way through this month, because the moment we've all been waiting for happens before the month is even half done",
  "You gained 2 minutes and 11 seconds",
  "You get 16 seconds more daylight today",
  "You get an extra 2 minutes and 10 seconds of daylight to get home in",
  "You got 1 minute and 12 seconds of extra daylight today, and sunset moved forward to 5.11pm",
  "You got 1 minute and 14 seconds of extra daylight, meaning today had a whole 15 minutes more daylight than you got on the solstice",
  "You got 1 minute and 19 seconds of extra daylight, and sunset ticked forward another minute to 5.15pm",
  "You got 1 minute and 43 seconds of extra daylight",
  "You got 1 minute and 52 seconds of extra daylight, too",
  "You got 1 minute and 55 seconds of extra daylight, too",
  "You got 1 minute and 9 seconds extra daylight",
  "You got 10 seconds of extra daylight today, and every day there will be more",
  "You got 11 hours and 47 minutes of daylight, and tonight the clocks change",
  "You got 15 extra seconds of daylight, a precious quarter-minute, and sunset ticked forward 1 minute to 4.57pm",
  "You got 2 minutes and 10 seconds of extra daylight",
  "You got 2 minutes and 14 seconds extra daylight, too",
  "You got 2 minutes and 18 seconds of extra daylight",
  "You got 2 minutes and 20 seconds of extra daylight, so I hope you made some use of them",
  "You got 2 minutes and 21 seconds of extra daylight, just today",
  "You got 2 minutes and 23 seconds of extra daylight today, sunrise went back to 6.41am and sunset to 6.03pm",
  "You got 2 minutes and 24 seconds extra daylight today",
  "You got 2 minutes and 7 seconds extra daylight",
  "You got 2 minutes and 8 seconds of extra daylight",
  "You got 2 whole extra minutes of daylight today, and you will get even more every day after today",
  "You got 25 extra seconds of daylight",
  "You got 29 extra seconds of daylight today",
  "You got 55 extra seconds of daylight today",
  "You got an extra 1 minute and 16 seconds of daylight just day",
  "You got an extra 41 seconds of daylight today",
  "You got an extra minute and 17 seconds of daylight today, and sunset moved forward to 5.13pm",
  "You got another 2 minutes and 17 seconds today, and sunrise is now all the way back to 6.54am, which is frankly pretty early",
  "You got this",
  "You have a long and glorious year of long evenings ahead of you",
  "You have nearly made it",
  "You have totally got this",
  "You mad it a whole week",
  "You made it out of 2015",
  "You made it through January",
  "You made it through the dark days of winter, and I'm so proud of you",
  "You might be leaving work in daylight today",
  "You survived February",
  "You were still lucky enough to get 2 minutes and 12 seconds of extra daylight today",
  "You'll get more than that",
  "You're doing it",
  "You're doing so well, stay with me",
  "You're getting there",
  "You're gonna love it",
  "You're gonna make it",
  "You're halfway through this final week",
  "You're really going to be noticing longer days now",
  "You're so close to the clocks changing now, dear one",
  "You've added 37 minutes of daylight since January 1, more than a minute per day",
  "You've added more than 5 minutes of daylight in 4 days, including 1 minute and 28 seconds today",
  "You've also made it halfway through February",
  "You've been doing really well, and I'm proud of you",
  "You've broken the back of the darkness now",
  "You've done so well to get this far, and I know you can make it to the end",
  "You've done so well",
  "You've made it all the way through January",
  "You’re already 12% of the way through January",
  "You’re making it",
  "You’ve gained 10 minutes just since Sunday",
  "You’ve gained 3 minutes of daylight since this time last week",
  "You’ve got 1 minute and 5 seconds of extra daylight, don’t waste them",
  "You’ve got 10 hours and 12 minutes of daylight to use today",
  "You’ve got this",
  "Your bonus day brings you a bonus 2 minutes and 23 seconds extra daylight, too",
  "Your reward for making it this far is 1 minute and 57 extra seconds of daylight",
  "Your reward is a whole hour more daylight each day than you had at the beginning of February",
  ".. boxing day? Who knows what boxing day is about anyway",
  '(And by "the clocks go back"I mean "the clocks go forward"obviously',
  ") it's the shortest month and the worst month, but we'll get through it together",
  "🎉🎉🎉YOU MADE IT",
  "1 minute and 10 seconds of extra daylight mean that days got 10 longer in 2017 so far",
  "1 minute and 11 seconds of precious extra daylight today",
  "1 minute and 12 seconds extra daylight today",
  "1 minute and 14 precious extra seconds of daylight today, and sunset ticked forward to 5.13pm",
  "1 minute and 15 seconds extra daylight today",
  "1 minute and 20 seconds of extra daylight got added today, and sunset moved forward to 5.15pm, which is almost okay",
  "1 minute and 25 seconds extra daylight",
  "1 minute and 4 seconds of extra daylight today took sunset to 5.09pm",
  "1 minute and 41 seconds of extra daylight today",
  "1 minute and 42 seconds of extra daylight today, and the sun set at 5.24pm",
  "1 minute and 43 seconds of extra daylight today, that’s 5 extra minutes in just 4 days",
  "1 minute and 45 seconds extra today",
  "1 minute and 46 seconds of extra daylight today means sunset ticked forward by *two* minutes, to 5.27pm",
  "1 minute and 49 seconds extra daylight today, that’s 38 minutes longer than the solstice was",
  "1 minute and 52 seconds of extra daylight arrived today, and it's Friday, so those are two good things",
  "1 minute and 6 seconds extra daylight today, sunset was at 5.10pm",
  "1 minute and 6 seconds of precious extra daylight today",
  "10 hours and 23 minutes of daylight today, a full two minutes more than just yesterday",
  "10 hours and 42 minutes of daylight today",
  "11 hours and 17 minutes of daylight today",
  "11 hours and 3 minutes of daylight today, a gain of 2 minutes and 16 seconds over yesterday",
  "11 hours and 36 minutes of daylight today",
  "11 hours and 8 minutes of daylight today",
  "2 minutes and 10 seconds of extra daylight today took sunrise back to 7.04am and sunset forward to 5.43pm",
  "2 minutes and 12 seconds more daylight today than yesterday",
  "2 minutes and 12 seconds of extra daylight today",
  "2 minutes and 14 seconds extra daylight gives us a 10 hour and 49 minute day, the longest since October 26th",
  "2 minutes and 15 seconds extra daylight today; the sun set at 5.49.",
  "2 minutes and 15 seconds of extra daylight today, for a total of 10 hours and 51 minutes",
  "2 minutes and 16 seconds extra daylight today, and the sun set at 5.51pm",
  "2 minutes and 17 seconds of extra daylight",
  "2 minutes and 19 seconds of extra daylight combined to push sunrise back to 6.52am and sunset forward to 5.55pm",
  "2 minutes and 2 extra seconds of daylight took sunrise back to 7.11am and sunset forward to 5.38pm",
  "2 minutes and 20 seconds extra daylight today, and another milestone is slowly approaching",
  "2 minutes and 20 seconds of extra daylight today carried sunset to 5.55pm",
  "2 minutes and 23 seconds extra daylight today",
  "2 minutes and 25 extra seconds of extra daylight took sunset out to 6.09pm, and we can deal with that",
  "2 minutes and 25 seconds extra daylight today",
  "2 minutes and 25 seconds of extra daylight today, and get ready, because tomorrow’s gonna be GREAT",
  "2 minutes and 25 seconds of extra daylight today, today was 11 and a half hours long",
  "2 minutes and 3 seconds of extra daylight took sunset to 5.37pm today",
  "2 minutes and 5 seconds of extra daylight made this double day happen",
  "2 minutes and 6 seconds extra daylight today",
  "2 minutes and 8 seconds of extra daylight, and the sunset was at 5.42pm",
  "2 minutes and 9 seconds extra daylight today",
  "22 extra seconds of daylight today, and the sun set at 4:58PM",
  "30 seconds of extra daylight are your reward for making it through the final Wednesday of 2020, the most cursed day of the most cursed year",
  "31 seconds more daylight today than yesterday",
  "40 whole extra seconds of daylight today",
  "44 seconds more daylight today, and the sun set at 5:03pm",
  "48 extra seconds of daylight to power you through hump day",
  "48 extra seconds of daylight today",
  "5.30pm",
  "5.45pm was sunset today",
  "58 seconds of extra daylight today",
  "9 hours and 51 minutes of daylight, 1 minute and 20 seconds more than yesterday",
  "9 hours, 37 minutes, 17 seconds of daylight today — 41 seconds more than yesterday",
  "91 extra seconds of daylight today",
  "A full 10 hours and 38 minutes of daylight today",
  "A minute and 44 extra seconds of daylight today gave us sunset at 5.26pm",
  "Alright, here we go: February",
  "Alright",
  "Alrightey: today you got 1 minute and 36 seconds of extra daylight",
  "An 11 hour day today",
  "An extra 1 minute and 43 seconds of sunlight today",
  "An extra 1 minute and 57 seconds of daylight today",
  "An extra 1 minutes and 41 seconds of daylight for you today",
  "An extra 2 minutes and 19 seconds of daylight got us to sunset at 5.56pm",
  "An extra 2 minutes and 24 seconds of daylight today, the longest day since October 8th last year",
  "An extra 2 minutes and 3 seconds of daylight today",
  "An extra minute and 26 seconds of daylight, as we grow tantalizingly close to 10-hour days again",
  "An extra minute and 50 seconds of daylight today, for 10 hours and 12 minutes of daylight in total",
  "An extra minute and 54 seconds of daylight today",
  "Another 17 seconds of daylight today",
  "Another 2 extra minutes of daylight today",
  "Another 2 minutes an 19 seconds of daylight added to our total today",
  "Another 2 minutes and 13 seconds extra daylight today",
  "Another 2 minutes and 16 seconds extra daylight today",
  "Another 2 minutes and 18 seconds of extra daylight, and the sun set at 5.53pm",
  "Another 2 minutes and 22 seconds took today to 11 hours and 16 minutes long",
  "Another 2 minutes and 24 seconds of daylight today",
  "Another 2 minutes and 25 seconds of precious daylight showed up for us today, pushing sunrise back to 6.34am and sunset to 6.08pm",
  "Another 2 minutes and 8 seconds of extra daylight today",
  "Another 35 seconds today — 5 extra minutes since Christmas",
  "Another 36 seconds of extra daylight today, and sunset ticked forward to 5.02. Stay with me",
  "Another double day, they're coming really close together now",
  "Another extra 1 minute and 49 seconds of daylight means we’ve gained 10 minutes since Monday",
  "Another extra minute and 46 second of daylight today",
  "Another mini milestone today: since the solstice the day has got a whole hour longer",
  "Another mini milestone",
  "Another minute and 24 seconds of daylight added today",
  "Another minute forward to 5.06pm for sunset, another 52 seconds of extra daylight",
  "Another whole minute and 7 extra seconds of daylight today",
  "Apologies for a burst of tweets just now, apparently my old connection to IFTTT from 2 years ago suddenly burped back into life?",
  "Awwwww yessssss the sun didn’t set until 6pm today",
  "Boom baby",
  "Clocks go forward tomorrow",
  "co/4HSPuOYWs5",
  "co/71OUSv3Z6C",
  "co/9EZFXVg6IH",
  "co/agZmVNDA2t",
  "co/bHoszvLijW",
  "co/BZkqRj0ruZ",
  "co/eKoIVKuhIX",
  "co/fe7lgXeva9",
  "co/o7mDS9M8hZ",
  "co/p68fz1wX0a",
  "co/SYKTNJHUuO",
  "co/TwEMWJxZrv",
  "Congratulations, you got a full 28 extra seconds of extra daylight today, and since last Monday you've added a whole 2 minutes of pure, unadulterated daylight",
  "Congratulations, you made it halfway through February",
  "Congratulations, you've made it halfway through January",
  "Congratulations",
  "Day four of sunset ticking forward",
  "Denizens of Dallas, good news",
  "Did you know that in just the last 2 weeks we've got more than 30 minutes of extra daylight? It's really steaming along now",
  "Did you know there’s an official definition of “twilight”? It’s also moving forward, and today it lasted until 6.17pm",
  "Double milestone day",
  "Due to some unscheduled dumbness, we accidentally scheduled all our tweets for last year",
  "Enjoy the first Monday of 2016 with more than 11 hours of daylight in it, and 2 minutes and 19 seconds more than yesterday",
  "Every day in February is at least a double day",
  "February continues to power along, adding 16 minutes of daylight just in the last 7 days",
  "February is more than 28% over already, and today was 2 minutes and 6 seconds longer than yesterday was",
  "February’s more than half gone, and we’re creeping up on some milestones",
  "For Valentine’s day I got you 2 minutes and 14 more seconds of daylight, in a day that was 10 hours, 47 minutes and 30 seconds long",
  "For Valentine’s day, I got you 10 hours and 46 minutes of precious, precious daylight",
  "For Valentine’s day, I got you 10 hours and 48 minutes of precious, precious daylight",
  "From now on, every day is at least a double day",
  "Good news from higher latitudes",
  "Good news: the earliest sunset was actually more than 2 weeks ago, on Dec 6th",
  "Happy 2013",
  "Happy Boxing Day :-) Today was 15 seconds longer than yesterday, and it keeps getting longer by more every day",
  "Happy Boxing day",
  "Happy Christmas Eve to you",
  "Happy double day Tuesday",
  "Happy Friday the 13th",
  "Happy hump day",
  "Happy leap day",
  "Happy Monday, this week has a major milestone so get hype",
  "Happy Monday",
  "Happy New Year's eve",
  "Happy New Year's Eve",
  "Happy New Year’s eve",
  "Happy New Year’s Eve",
  "Happy New Year",
  "Happy solstice to you",
  "Happy Thursday",
  "Happy Valentine’s day",
  "Happy",
  "Have a happy new year’s eve",
  "Hello everyone",
  "Hello new followers",
  "Hooray, the sun set after 5.30 today for the first time since November 1",
  "Hope you enjoyed your first 11-hour Saturday since October 20th",
  "Hump day today is a triple day: sunrise went back 1 minute to 7.04am, sunset jumped forward 2 minutes to 5.46pm",
  "Hump day",
  "I hope your Sunday was a fun day",
  "I hope your Sunday was full of sun",
  "I hope your Sunday was really a day of sun -- there were 53 seconds of extra daylight to use today, and sunset moved forward a minute to 5.05pm, which is a whole 15 minutes later than it was on the solstice",
  "I hope your Sunday was sunny",
  "I'm back, my darlings",
  "I'm coming back soon, my darlings",
  "In just 10 days sunset has moved forward by 10 minutes, and because sunrise is moving backwards you added 12 minutes of actual daylight",
  "In just 10 days, we've accumulated 20 extra minutes of daylight, making today 10 hours and 36 minutes long",
  "In just 5 days, we've added 7 whole minutes of daylight",
  "In just the last 3 days you've added more than 3 minutes of daylight",
  "In the last 10 days we've got 20 minutes of extra daylight",
  "In the last 3 days alone you've got 6 extra minutes of daylight",
  "In the past 30 days, we've added 33 whole minutes of daylight: more than a minute per day, on average",
  "Is the 26th called Boxing Day where you are? Anyway, happy Whatever This Day Is Called",
  "It has been 7 days since the solstice",
  "It may be Monday, but take heart, it's another triple day: sunrise moved backwards 2 minutes to 6.55am, sunset forwards to 5.51pm, and there were 2 minutes and 17 seconds of extra daylight",
  "It may only be Tuesday, but you got 2 minutes and 25 seconds more daylight today",
  "It's 6pm and there's still light in the sky",
  "It's a beautiful day to say good bye to dark nights",
  "It's a big milestone today: today had 10 whole hours of daylight",
  "It's a double day, but today's milestone is the length of the day: today there were 10 hours of daylight",
  "It's a double day: sunrise back to 7.16am, sunset forward to 5.32pm",
  "It's a double day: sunrise went back to 7.13am and sunset forward to 5.35pm",
  "It's a milestone day: it's our first double day",
  "It's a milestone day",
  "It's a milestone today: today for the first time we added *2 whole minutes* of daylight, just today",
  "It's a mini milestone day",
  "It's a mini milestone today",
  "It's a teeny-tiny mini milestone today: the sun set at 5.45pm",
  "It's a triple day, back-to-back with yesterday's triple day",
  "It's another double day",
  "It's another milestone today: not only is it a double day, but every day from now on is going to be a double day or better",
  "It's been 7 days since the solstice",
  "It's Boxing Day",
  "It's Friday, which means this weekend you won't have to go to work or come back in the dark, you can wander around in the daylight -- and there were 47 more seconds of daylight to do that today",
  "It's hump day and a double day: sunrise is all the way back to 7.11am, sunset goes forward to 5.38pm, and you got 2 whole minutes and 2 seconds of extra daylight today",
  "It's January 16th: you've made it halfway through January",
  "It's Monday, and for a lot of you this will be your first day back at work for a while",
  "It's Monday, but take heart: we've added more than 5 minutes of daylight just since February 1. Sunset moved forward to 5.36pm, and you got 2 minutes and 1 second of extra daylight",
  "It's Sunday and a double day",
  "It's Sunday, and you got more daylight -- 1 minute and 6 seconds of it, meaning you've gained 1 minute per day every day for a week now",
  "It's Sunday, and you had a whole 10 hours and 10 minutes of daylight, because today you got 1 minutes and 48 seconds of extra daylight",
  "It's the last Wednesday of January and it's also a milestone: sunset was at 5.30pm today",
  "It's the solstice",
  "It's yet another double day",
  "It’s a *triple* day: sunrise went back 1 minute to 7.15am, sunset went forward 2 minutes to 5.30pm",
  "It’s a double day again",
  "It’s a double day: sunrise went back to 7.21am, sunset forward to 5.22pm, and 1 minute and 39 seconds of extra daylight",
  "It’s a double day",
  "It’s another double day: sunrise moved back to 7.21am, sunset moved forward to 5.20pm",
  "It’s boxing day",
  "It’s Friday",
  "It’s just a trick of the clock, but the sun set at 4:55PM today instead of 4:54PM",
  "It’s Monday, but on the bright side, this Monday has 15 minutes more daylight than last Monday did",
  "It’s Sunday, so I hope you found some sun",
  "It’s the last day of winter time, thank goodness",
  "Just 4 more days until we turn things around",
  "Just since February started we've added 32 minutes of daylight to the day",
  "March is a piece of cake",
  "Monday may suck, but take heart: this is the last Monday before the clocks change",
  "Mondays are no fun, but in the last 9 days sunset has moved forward by a minute every single day, and that's going to keep happening every day",
  "Mondays aren't my favorite day, but this Monday is the longest day of the year so far, with 1 minute and 9 seconds more daylight than yesterday",
  "Mondays can be hard, but focus on the little things: was it maybe a bit brighter today? Sunset ticked forward to 5.06pm, and there were 56 seconds of extra daylight",
  "Mondays suck, but this Monday had 10 minutes more daylight than last Monday, so there’s that",
  "More than 2 minutes of extra daylight today",
  "More than 30 seconds of extra daylight got added today",
  "Nearly 2 minutes of extra daylight today",
  "Never mind the Valentine thing; celebrate an extra 2 minutes and 14 seconds of daylight",
  "No more dark Wednesdays after this one, and it's a triple day",
  "Okay, February’s underway, and we can do this",
  "Okay, it’s March",
  "Okay, my friends",
  "Okay, this is terrible",
  "Okay",
  "OMG this is the final dark Tuesday of the year",
  "Only 2 more days until the clocks change",
  "Only 3 more days until the clocks change",
  "Only 5 more days until the clocks change",
  "Oops: I meant *sunset* moves forward to 5.17pm obviously",
  "Our second mini-milestone: sunset was at 5pm today",
  "Say goodbye to the old year with 33 seconds of extra daylight -- today was a whole minute longer than just 2 days ago",
  "SFGate did an article about us",
  "Sick of the darkness already? This account comes back to life Dec 21",
  "Since January 1st we've added more than 90 minutes to the length of the day",
  "Since the solstice, sunset has moved forward a whole hour",
  "Stick with me until Friday, it’s a nice big milestone",
  "Sun set was at 5.50pm",
  "Sunday, hopefully fun day, definitely a double day",
  "Sunrise at 6.37am, sunset at 6.06pm, and 11 hours and 29 minutes of daylight in between",
  "Sunrise had still been getting later, but now that’s turned around too",
  "Sunrise is all the way back to 6.37am, sunset ticked forward to 6.06pm, and everything’s gonna be okay",
  "Sunrise is back to 6.31am, which is just early",
  "Sunrise is back to 6.51am and sunset was at 5.55pm",
  "Sunrise is back to 7.09am, sunset forward to 5.39pm, for a day that is 10 hours and 30 minutes long",
  "Sunrise keeps rolling back, to 7.05am today, and sunset has reached 5.44pm",
  "Sunrise moved back by 1 minute to 7.23am, and sunset moved forward to 5.14pm, plus there was 1 minute and 21 seconds more daylight to be in",
  "Sunrise moved back to 6.36am, sunset moved forward to 6.06pm, and today’s a milestone: 11 and a half hours of daylight",
  "Sunrise moved back to 6.47am today, sunset kept moving forward and hit 5.58pm",
  "Sunrise moved back to 6.54am, sunset moved forward to 5.53pm, and tomorrow’s a milestone day",
  "Sunrise slipped back 2 minutes to 6.48am, which is kind of annoyingly early, right? Sunset was at 5.58pm",
  "Sunrise ticked back 2 minutes to 6.44am, sunset forward by 1 minute to 6.01pm, and there were 2 minutes and 22 seconds extra daylight",
  "Sunrise ticked back by a minute today to 7.22am, and sunset forward by a minute to 5.20pm",
  "Sunrise ticked back to 7.01am today, and sunset today ticked forward 2 minutes to 5.48pm",
  "Sunrise ticked back to 7.04am, sunset ticked forward to 5.44pm",
  "Sunrise ticked back to 7.13am, sunset ticked forward to 5.34pm, and tomorrow is another little milestone day, so hang on",
  "Sunrise ticked back to 7.17am, sunset ticked forward to 5.29pm, for a full 10 hours and 12 minutes of daylight",
  "Sunrise ticked backwards by 1 minute for the first time since July",
  "Sunrise ticked backwards to 7.24am and sunset forwards to 5.14pm",
  "Sunrise was 7.01am today, sunset was 5.46pm, and there were 2 minutes and 14 seconds of extra daylight",
  "Sunrise was 7.02am today, sunset was 5.45pm: just 15 more minutes to go to the 6pm milestone, we’ll be there before you know it",
  "Sunrise was a way-early 6.36am, sunset wasn’t until 6.07pm, and we’re cruising to the time change",
  "Sunrise was at 6.29am today, sunset was at 6.11pm",
  "Sunrise was at 6.46am, which is really early, and sunset was at 5.59pm after 2 minutes and 21 seconds of extra daylight",
  "Sunrise was at 6.57am today, having broken through the 7am barrier yesterday",
  "Sunrise was at 6.59am, which is frankly as early as I need it to be",
  "Sunrise was at 7.06am today, which is honestly as early as I need it to be, and sunset was at 5.41pm",
  "Sunrise was at 7.24am, 1 minute earlier than yesterday",
  "Sunrise was at 7am",
  "Sunrise was before 7am today for the first time since November 25th",
  "Sunrise was positively decent today at 6.43am, and sunset wasn’t until 6.02pm",
  "Sunrise went back 1 minute, sunset went forward one minute to 5.16pm, and it was Sunday",
  "Sunrise went back to 6.32am, sunset went forward to 6.09pm, and we are nearly, nearly there",
  "Sunrise went back to 6.35am today, and sunset didn’t happen until 6.08pm",
  "Sunrise went back to 6.50am today, sunset forward to 5.56pm",
  "Sunrise went back to 7.03am and sunset has got as far as 5.45pm",
  "Sunrise went back to 7.04am, sunset went forward to 5.44pm, and it’s Thursday",
  "Sunrise went back to 7.12am, sunset went forward to 5.35pm, and tomorrow you’re in for a treat",
  "Sunset at 5.22pm today, after 10 hours, 1 minutes, and 38 seconds of precious daylight",
  "Sunset moved another minute forward to 5.02pm today, and there were 40 whole seconds of extra daylight",
  "Sunset moved back to 5.18pm",
  "Sunset moved forward again to 5.13pm, and there was 1 minute and 19 seconds of extra daylight",
  "Sunset moved forward by another minute today, to 5.09pm, and you got a minute and 7 seconds of extra daylight",
  "Sunset moved forward to 5.15pm today",
  "Sunset moved forward to 5.20pm today, there was 1 minute and 35 seconds of extra daylight, and tomorrow's a BIG milestone",
  "Sunset ticked forward 2 minutes to 5.51pm today, and sunrise back to 6.56am, which is pretty early",
  "Sunset ticked forward another minute to 4.58pm today, and today was 23 seconds longer than yesterday",
  "Sunset ticked forward another minute to 5.05pm, and you got another 49 seconds of daylight",
  "Sunset ticked forward by 1 minute to 4.58, and we’ve gained a whole minute of extra daylight since the solstice",
  "Sunset ticked forward by another minute to 4.59, and today had 22 seconds more daylight than yesterday",
  "Sunset ticked forward by another minute today to 4.59pm",
  "Sunset ticked forward by two minutes today to 5.37pm, and today is 14 minutes longer than last Wednesday was",
  "Sunset ticked forward to 4.57pm today, and you got 16 extra seconds of daylight – a whole quarter-minute",
  "Sunset ticked forward to 5.04pm again, that's two days in a row it's done that",
  "Sunset ticked forward to 5.08pm today, and there were 59 seconds of extra daylight",
  "Sunset ticked forward to 5.12pm today",
  "Sunset ticked forward to 5.53pm, sunrise was 6.55am, and it’s Friday",
  "Sunset today was at 5.07pm, and we've hit our latest mini milestone: we had a whole minute of extra daylight today",
  "Sunset today was at 5.54pm, a minute later, and sunrise today was 6.55am, a minute earlier",
  "Sunset was 5.12pm today",
  "Sunset was 5.20pm, sunrise went back to 7.22am, and Friday’s looking closer",
  "Sunset was at 4:59PM today, and today is the last time it’ll be before 5PM",
  "Sunset was at 5.03pm today",
  "Sunset was at 5.04pm today, and you got 46 seconds extra daylight",
  "Sunset was at 5.04pm today",
  "Sunset was at 5.05pm today, which is 5 minutes later than last Thursday",
  "Sunset was at 5.07pm, and you got 59 seconds of extra daylight",
  "Sunset was at 5.07pm",
  "Sunset was at 5.08pm today – that’s 10 minutes later than just 12 days ago",
  "Sunset was at 5.08pm, that’s 11 minutes later than Christmas day, and today was a whole extra minute longer",
  "Sunset was at 5.09pm today, 1 minute and 3 seconds later than yesterday",
  "Sunset was at 5.10pm today, it hasn’t set that late since November 2nd last year",
  "Sunset was at 5.11pm today, 1 minute and 9 seconds later than yesterday",
  "Sunset was at 5.12pm, which is the latest it’s been since the clocks went back in October",
  "Sunset was at 5.13pm today, and bonus",
  "Sunset was at 5.14pm, after 9 hours and 49 precious minutes of daylight",
  "Sunset was at 5.14pm, which is a whole 20 minutes later than it was on the solstice",
  "Sunset was at 5.16pm; after 9 hours and 52 minutes of daylight",
  "Sunset was at 5.18pm today, after 1 minute and 28 seconds more daylight than you got just yesterday",
  "Sunset was at 5.18pm; you got a minute and 28 seconds of extra daylight over yesterday",
  "Sunset was at 5.19pm, after 9 hours and 57 minutes of daylight",
  "Sunset was at 5.20pm",
  "Sunset was at 5.25pm today",
  "Sunset was at 5.29pm today, and you got 1 minute and 52 seconds of extra daylight",
  "Sunset was at 5.32pm today — we’ve gained a whole 30 minutes since the start of the month",
  "Sunset was at 5.35pm today — our first two-minute jump is tomorrow",
  "Sunset was at 5.36pm today, sunrise was at 7.11am, and today was a decent 10 hours and 24 minutes long",
  "Sunset was at 5.37pm today, with 2 minutes and 2 seconds extra daylight",
  "Sunset was at 5.38pm today and today was 2 minutes and 3 seconds longer than yesterday",
  "Sunset was at 5.41pm",
  "Sunset was at 5.45pm today, the longest day since October 29th last year",
  "Sunset was at 5.57pm today, and you got 2 minutes and 20 seconds of extra daylight",
  "Sunset was at 5.58pm today, which is 57 whole minutes later than January 1.",
  "Sunset was at 5.59pm today - that’s 24 minutes later than it was on the 1st of February",
  "Sunset was at 5.59pm today",
  "Sunset was at 6.05pm today, which is 71 minutes later than it was on the solstice",
  "Sunset was at 6.08pm today",
  "Sunset was at 6.09pm today, which is like, a totally manageable time for the sun to set",
  "Sunset was at 6.11pm, and we’re gonna be fine",
  "Sunset was at 6.12pm today, there were 2 minutes and 26 seconds extra daylight, and we’re nearly there",
  "Sunset was at 6.13pm today, and the week’s nearly over too",
  "Sunset was at 6.15pm today and the clocks change TOMORROW",
  "Sunset was at 6.39am, which is damn early, and today was 11 hours and 24 minutes long",
  "Sunset wasn’t until 5.24pm today, I hope you got to see some of it",
  "Sunset went forward to 5.03pm today",
  "Sunset went forward to 5.27pm, sunrise went back to 7.18am, we’re gonna make it",
  "Take courage",
  "Take heart, my friends",
  "The clocks change this weekend",
  "The days keep racking up more daylight",
  "The end of February is now in sight, and you got 2 minutes and 20 seconds of extra daylight to prove it",
  "The sun didn’t set until 5:03 today",
  "The sun rose at 7.19am today, 6 minutes earlier than it did on the 1st of January",
  "The sun rose at 7.24am today, a minute earlier than yesterday",
  "The sun set 1 minute later today than yesterday, at 5.23.",
  "The sun set 1 minutes and 30 seconds later than it did yesterday",
  "The sun set 3 minutes later than Jan 1 today, at 5.05pm",
  "The sun set 8 minutes later today than it did this day last week",
  "The sun set after 5.30 today for the first time since November 3rd",
  "The sun set after 5.45 today, for the first time since November 3rd",
  "The sun set after 5pm todayYou gained another 24 seconds of daylight",
  "The sun set after 6pm today",
  "The sun set at 4:58pm again, but there were 20 extra seconds of daylight today",
  "The sun set at 4:59pm, 27 seconds later than yesterday",
  "The sun set at 4.56pm today instead of 4.55pm",
  "The sun set at 4.58pm today",
  "The sun set at 4.59pm today",
  "The sun set at 5:05pm today, 51 seconds later than yesterday",
  "The sun set at 5.04pm today, which is 10 whole minutes later than it did on the solstice",
  "The sun set at 5.06pm today, which is the latest it’s been since the clocks went back in October",
  "The sun set at 5.06pm, after 54 seconds more daylight than yesterday",
  "The sun set at 5.12pm",
  "The sun set at 5.17pm today, 8 minutes later than last Tuesday",
  "The sun set at 5.20 today; 9 minutes longer than last Sunday",
  "The sun set at 5.27 today; an extra one minute and 47 seconds of daylight",
  "The sun set at 5.29 today; today was 111 seconds longer than yesterday",
  "The sun set at 5.38pm today, and dawn has gained another 5 minutes — it was at 7.10am today",
  "The sun set at 5pm today",
  "The sun set at 6.02 today, after 2 minutes and 22 seconds more daylight than yesterday",
  "The sun set at 6.10 today, 10 minutes later than just 12 days ago",
  "The sun set of 4.57pm today, and there were 5 seconds of extra daylight",
  "The sun will set at 5.21pm today, after a full 1 minute and 34 seconds more daylight than yesterday",
  "There are two mini milestone today",
  "There were 10 hours and 26 minutes of daylight today, 2 minutes more than yesterday",
  "There were 2 minutes and 6 seconds of extra daylight today",
  "There were nine hours and 34 minutes of daylight today",
  "There’s less than a week left in January, the end of this crappy month is in sight",
  "Third day in a row of sunset ticking forward",
  "This is it: the darkest day of the year",
  "This is last day of the last week of crappy, short days of winter",
  "This is the last dark, crappy Thursday",
  "This is the last Monday of 2020, and you've got 23 extra seconds of daylight -- we're really beginning to rack up the daylight now",
  "This is the last weekend of January",
  "This Monday the sun will set 8 minutes later than it did last Monday",
  "This Sunday is the last Sunday you’ll have less than 11 hours of daylight in, and tomorrow’s another milestone",
  "This Sunday the sun set at 6.02pm, which is 7 minutes later than last Sunday",
  "This Sunday was 2 minutes and 12 seconds longer than Saturday was",
  "This Sunday you get 1 minute and 58 whole seconds of extra daylight, plus it's a double day: sunrise went back to 7.14am and sunset went forward to 5.34pm, which is really beginning to be okay",
  "To get you through Monday, have 1 minute and 54 extra seconds of daylight",
  "Today added another 2 minutes and 24 seconds of daylight to your total",
  "Today had 1 minute and 31 seconds more daylight than yesterday: a whole minute and a half",
  "Today had 10 hours and 36 minutes of daylight, which is 10 minutes more just since Saturday",
  "Today had 10 hours and 47 seconds of daylight",
  "Today had 10 hours, 9 minutes and 26 seconds of daylight; that's 1,991 seconds more than January 1",
  "Today had 11 hours and 15 minutes of daylight, the longest day since October 14th 2019. That last 15 minutes all showed up just in the last 7 days, as we pile on the minutes at speed right now: 2 minutes and 22 seconds of extra daylight today",
  "Today had 2 minutes and 25 seconds more daylight than yesterday did",
  "Today had 3 seconds of daylight more than yesterday",
  "Today had 50 seconds more daylight than yesterday did",
  "Today had 9 hours and 58 minutes of daylight in it, the longest day since November 20th last year",
  "Today has 10 hours and 18 minutes of daylight, 13 minutes more than this day last week",
  "Today is 3 seconds longer than yesterday",
  "Today is the first 11-hour day since October 20",
  "Today is the last day the sun sets before 6pm",
  "Today is the longest day since November 30th, 2020",
  "Today is the longest day since October 27th last year, and was 2 minutes and 14 seconds longer than yesterday",
  "Today sunrise moved back to 7.09am, sunset moved forward to 5.37pm, and you’re already 18% of the way through February",
  "Today sunrise started ticking backwards",
  "Today sunrise went back 1 minute to 6.38am, which is pretty damn early, and sunset forward to 6.05pm",
  "Today sunset skipped forward *two* minutes",
  "Today sunset was at 5.08pm, and the day was 1 minute and 3 seconds longer than yesterday",
  "Today sunset was at 5.15pm, which is beginning to be manageable again",
  "Today the sun rose at 7.12am, a gain of 2 minutes over just 2 days",
  "Today the sun rose at 7.25am, a minute sooner than it did yesterday",
  "Today the sun set at 4.59pm",
  "Today the sun set at 5.06pm",
  "Today the sun set at 5.07pm, a minute later than it did yesterday",
  "Today the sun set at 5.10pm, 1m8s later than yesterday",
  "Today the sun set at 5.25pm, 1 minute and 43 seconds later than yesterday",
  "Today the sun set at 5.31pm",
  "Today the sun set at 5.32, after 13 minutes more daylight than this day last week",
  "Today the sun set at 5.33; today was 42 minutes longer than January 1",
  "Today the sun set at 5.34pm",
  "Today the sun set ticked forward to exactly 5pm",
  "Today the sunrise went back by 1 to 7.17am and sunset went forward by 1 to 5.28pm",
  "Today the sunset was at 4.55pm",
  "Today there were 10 minutes more daylight than there were last Tuesday",
  "Today there were 19 seconds more daylight than yesterday, and we've hit our first tiny milestone: today was a whole minute longer than the solstice was",
  "Today there were 9 hours and 44 minutes of daylight, 1 minute and 5 seconds more than yesterday",
  "Today there were 9 hours and 46 minutes of sunshine, 7 minutes more than this day last week",
  "Today there were 9 hours and 50 minutes of daylight, the most since November 26th last year",
  "Today was 1 minute 30 seconds longer than yesterday, and sunset wasn’t until 5.19pm",
  "Today was 1 minute and 26 seconds longer than yesterday",
  "Today was 1 minute and 39 seconds longer than yesterday, 10 minutes longer than last Saturday",
  "Today was 1 minute and 41 seconds longer than yesterday",
  "Today was 1 minute and 43 seconds longer than yesterday, closing in on 2 minutes extra per day",
  "Today was 1 minute and 51 seconds longer than yesterday",
  "Today was 1 minute and 58 seconds longer than yesterday",
  "Today was 10 and a half hours long, the longest day since November 3.",
  "Today was 10 hours and 11 minutes long, which is 14 minutes longer than last Thursday",
  "Today was 10 hours and 15 minutes long, the most daylight since November 10th last year",
  "Today was 10 hours and 2 minutes long, which is a whole 30 minutes longer than the solstice was",
  "Today was 10 hours and 3 minutes long, a full 30 minutes longer than days were on the solstice",
  "Today was 10 hours and 30 minutes long, an extra 10 minutes since Friday",
  "Today was 10 hours and 30 minutes long",
  "Today was 10 hours and 32 minutes long, which is a whole hour longer than the day was on the solstice",
  "Today was 10 hours and 32 minutes long, which is a whole hour longer than the solstice was",
  "Today was 10 hours and 32 minutes long",
  "Today was 10 hours and 37 minutes long, which is the longest day since October last year",
  "Today was 10 hours and 39 minutes long",
  "Today was 10 hours and 40 minutes long – 10 minutes more just since Tuesday",
  "Today was 10 hours and 52 minutes long; 2 minutes and 15 seconds longer than yesterday",
  "Today was 10 hours and 55 minutes long, which is 15 minutes longer than last Wednesday was",
  "Today was 10 hours and 56 minutes long, and had 2 minutes and 19 seconds more daylight than yesterday",
  "Today was 10 hours and 57 minutes long, which is pretty good",
  "Today was 10 hours and 57 minutes long; an extra 16 minutes since this day last week",
  "Today was 10 hours long, the first 10-hour day since November 19th",
  "Today was 10 HOURS LONG",
  "Today was 10 hours, 3 minutes and 22 seconds long",
  "Today was 10 minutes longer than just last week Tuesday",
  "Today was 10 seconds longer than yesterday",
  "Today was 11 hours and 15 minutes long, which is honestly not bad",
  "Today was 11 hours and 16 minutes long, which is a pretty good Saturday",
  "Today was 11 hours and 26 minutes long, the longest since October 10th last year",
  "Today was 11 hours and 27 minutes long, and sunset was at 6.05pm",
  "Today was 11 hours and 30 minutes long",
  "Today was 11 hours and 32 minutes long, which means we've added 2 whole hours to the length of the day since the terrible, dark days of the solstice",
  "Today was 11 hours and 38 minutes long, which is a whole extra hour since just the 10th of February",
  "Today was 11 hours and 38 minutes long",
  "Today was 11 hours and 39 minutes long; we’ve added 10 minutes just since Sunday",
  "Today was 11 hours and 5 minutes long, which isn’t bad at all",
  "Today was 11 hours and 6 minutes long, an extra 10 minutes since Monday",
  "Today was 11 hours and 6 minutes long",
  "Today was 11 hours long, and sunset was at 5.54pm, a whole hour later than it was on the solstice",
  "Today was 12 minutes longer than Sunday was last week, and 1 minute and 44 seconds longer than yesterday",
  "Today was 14 minutes longer than last Tuesday",
  "Today was 17 minutes longer than last Monday was",
  "Today was 1m 14s longer than yesterday",
  "Today was 1m 19s longer than yesterday; tomorrow will be 1m 22s longer than that",
  "Today was 2 minutes 18 seconds longer than the day before",
  "Today was 2 minutes 2 seconds longer than yesterday",
  "Today was 2 minutes and 1 second longer than yesterday",
  "Today was 2 minutes and 12 seconds longer than yesterday was, and sunset wasn’t until 5.47pm",
  "Today was 2 minutes and 15 seconds longer than yesterday was",
  "Today was 2 minutes and 17 seconds longer than yesterday",
  "Today was 2 minutes and 23 seconds longer than yesterday, and a full hour longer than February 1st",
  "Today was 2 minutes and 4 seconds longer than yesterday, and at 10 hours and 29 minutes was the longest day since November 3.",
  "Today was 2 minutes and 7 seconds longer than yesterday, meaning today was a full hour longer than the solstice",
  "Today was 2 seconds longer than yesterday",
  "Today was 33 minutes longer than the solstice was",
  "Today was 4 seconds longer than yesterday",
  "Today was 45 minutes longer than the solstice was",
  "Today was 5 seconds longer than yesterday — twice the size of yesterday’s gain",
  "Today was 5 seconds longer than yesterday",
  "Today was 58 seconds longer than yesterday",
  "Today was 6 seconds longer than yesterday",
  "Today was a double day",
  "Today was a triple day: sunrise went back 2 minutes to 6.48 and sunset forward to 5.59pm",
  "Today was a whole minute and 13 seconds longer than the day before",
  "Today was a whole minute and a half longer than yesterday",
  "Today was another 2 minutes and 16 seconds longer",
  "Today was one whole minute longer than yesterday",
  "Today was the first day the sunset moved forward by 2 minutes – it was 5.18pm today",
  "Today was the longest day since November 15th last year, a full 10 hours and 7 minutes long",
  "Today was the longest day since November 30",
  "Today you get 1 minute and 46 seconds of extra daylight, and sunset moved forward to 5.26pm",
  "Today you got 1 minute and 10 seconds of extra daylight, which is a lot",
  "Today you got 1 minute and 25 seconds extra daylight than you did just yesterday, which means you've added 10 whole minutes of daylight just in the last week",
  "Today you got 1 minute and 40 seconds of extra daylight",
  "Today you got 2 extra seconds of daylight",
  "Today you got 2 minutes and 11 seconds of extra daylight",
  "Today you got 2 minutes and 9 seconds of extra daylight, sunrise went backwards to 7.06am, and sunset went forwards to 5.43pm",
  "Today you got a minute and 58 extra seconds of daylight",
  "Today you got not 1 but 2 whole extra minutes of daylight",
  "Today's a double day, and a mini milestone",
  "Today's a triple day: sunrise hopped back 2 minutes to 6.57am, sunset was aided by 2 minutes and 17 seconds of extra daylight and got to 5.52pm",
  "Today's milestone: today was more than 11 hours long",
  "Today's mini milestone is quite mini, but you got 1 and a half minutes of extra daylight",
  "Today's mini milestone: in 30 days we've added a whole hour to the day",
  "Today’s the last day the sun sets before 6pm",
  "Tonight is the solstice, the very longest night of the year",
  "Two milestones today",
  "Two minutes and 21 seconds of extra daylight today",
  "TWO WHOLE MINUTES of extra daylight today, and every day after today",
  "Ugh, Monday",
  "Ugh",
  "Uh, I mean sunrise",
  "Usually we'd be celebrating the end of February today, but it's a leap year so there's one more day of this cursed month",
  "Wahey",
  "We are gaining more than 1 minute and 50 seconds of extra daylight every day from here on out",
  "We are on the last week before DST",
  "We are really racking up daylight now: another 1 minute and 41 seconds just today; that's more than 30 minutes in 30 days",
  "We have hit our first mini-milestone: today the sun set at 4.56pm, 1 minute later than yesterday",
  "We have reached sunset at 5.30pm",
  "We made it",
  "WE MADE IT",
  "WE'RE HERE",
  "We're really going to start racking up the minutes now",
  "We've been racking up more than a minute of daylight per day for a whole week now",
  "We've finally reached the end of February",
  "We've gained 10 minutes of daylight in just 6 days, and it was another double day",
  "Wednesday",
  "Welcome back to Here Comes The Sun",
  "Welcome to 2014",
  "Welcome to 2017",
  "Welcome to a major milestone",
  "Welcome to a triple day Monday",
  "Welcome to March, this is the home stretch",
  "Welcome to our latest mini milestone",
  "Welcome to the 14th of January: in the last 14 days you've gained 13 minutes of daylight, and sunset has moved by 13 minutes too",
  "Welcome to the final week of January",
  "Why the heck is it called Boxing Day? Anyway, sunset ticked over to 4:57PM today, and we’re gonna be okay",
  "With 2 minutes and 16 seconds extra daylight, today was 16 minutes longer than last Thursday",
  "With an extra 1 minute and 34 seconds of daylight, today’s the longest day since November 20th last year",
  "With nearly two and a half minutes of extra daylight today, I bet you can feel the days getting better",
  "With sunset at 5.21pm, today was 10 hours long",

  "WOOOO big milestone today: sunset wasn't until 6pm",

  "Would you believe since the beginning of February we've already added 4 minutes of daylight? It's accumulating really fast now",

  "Yesterday the sun set at 4.55pm today, and today it set at 4.56pm",
  "Yet another double day",
  "You are 82% of the way through February",
  "You are halfway through the crappy dark days of March",
  "You can take the edge off of Monday by celebrating a triple day: sunrise went back by 2 minutes to 7.03am, and sunset went forward to 5.44pm",
  "You got 1 minute and 2 seconds extra daylight; that’s 10 minutes extra since the solstice",
  "You got 1 minute and 20 seconds of extra daylight today, and as of sunset, January is nearly half over",
  "You got 1 minute and 21 seconds of extra daylight today, and tomorrow is a double day",
  "You got 1 minute and 35 seconds extra daylight today, and stay with me, because tomorrow’s a big milestone",
  "You got 1 minute and 55 seconds of extra daylight today",
  "You got 1 minute and 6 seconds of extra daylight today, and sunset moved forward again to 5.09pm",
  "You got 1 minutes 25 seconds extra daylight today",
  "You got 18 seconds of extra daylight today, that’s a whole extra minute since the solstice",
  "You got 2 minutes and 18 extra seconds of precious daylight today",
  "You got 2 minutes and 24 extra seconds of daylight today, and the end is in sight",
  "You got 2 minutes and 8 seconds of extra daylight today, which really starts to add up fast",
  "You got 2 minutes and 9 seconds extra daylight today than you did yesterday, and 10 hours and 38 minutes of daylight in total",
  "You got 21 extra seconds of daylight today – more than a minute of extra daylight since the solstice",
  "You got 21 extra seconds of daylight today, and sunset ticked forward again, to 4.58pm",
  "You got 24 extra seconds of daylight today",
  "You got 26 seconds of extra daylight today",
  "You got 33 seconds of extra daylight today, and 2014 is finally behind us",
  "You got 34 extra seconds of daylight today",
  "You got 42 seconds more daylight today",
  "You got 45 extra seconds of daylight today",
  "You got 53 extra seconds of daylight today, and the sun set at 5.06pm",
  "You got 57 seconds of extra daylight today, and you should look forward to tomorrow, not just because it's Friday, but because it's two big milestones",
  "You got 8 seconds of extra daylight today",
  "You got 9 hours and 52 minutes of daylight today",
  "You got 90 whole seconds extra daylight today",
  "You got a whole 45 extra seconds of daylight today, and it was a Saturday, so I hope you got out of the house to enjoy them",
  "You got a whole, glorious 1 minute and 15 seconds of extra daylight today, and sunset got pushed back yet another minute to 5.13pm",
  "You got an extra 1 minute and 40 seconds of daylight today",
  "You got another 2 minutes and 4 seconds of daylight today, that’s nearly an hour extra since the solstice",
  "You got another 56 seconds of extra daylight",
  "You made it another day",
  "You made it through January",
  "You made it through Thursday, and to reward you the sunset ticked forward yet another minute to 5.03pm",
  "You made it through to the first weekend of the year, and in the last 7 days you gained at least a whole minute of extra daylight",

  "YOU MADE IT",
  "You may be back at work today, but sunset was at 5.04pm today, and today was 46 seconds longer than yesterday",
  "You've hit your first milestone",
  "You've made it halfway through January",
  "You've made it halfway through the week",
  "You’re more than halfway through February",
  "You’ve gained 5 minutes of extra daylight since the year started",
  "You’ve got February in the bag, just one more day",
  "You’ve got it from here — see you next year",
]
